# Generated by Django 2.2 on 2021-07-29 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=100)),
                ('LastName', models.CharField(max_length=100, unique=True)),
                ('Profilepicture', models.CharField(max_length=100)),
                ('EmailAddress', models.CharField(max_length=100, unique=True)),
                ('PhoneNumber', models.CharField(max_length=100)),
                ('RoomNumber', models.CharField(max_length=100)),
                ('Subjectstaught', models.CharField(max_length=1000)),
            ],
            options={
                'db_table': 'Teachers',
            },
        ),
    ]
