# Generated by Django 2.2 on 2021-07-29 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0002_teachermodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachermodel',
            name='LastName',
            field=models.CharField(max_length=100),
        ),
    ]
